export const PRICE_TEMPLATE  = [
    {
        "id": "dd44b867-2424-4671-a3be-434c53a975ea",
        "ccy": "VND",
        "denominations": 500000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": "camntn",
        "checker_date": "2022-08-19T17:24:10",
        "ord": 1,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "d8503a73-7ada-4caa-b588-ca42820b1c82",
        "ccy": "VND",
        "denominations": 200000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": "hieupx",
        "checker_date": "2022-04-21T10:56:08",
        "ord": 2,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "99eb183a-293e-4529-9dd7-fe9a06ec761b",
        "ccy": "VND",
        "denominations": 100000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": "hieupx",
        "checker_date": "2021-06-08T15:14:06",
        "ord": 3,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "39d21a32-be8e-4e64-a976-7eb5f8f18cbe",
        "ccy": "VND",
        "denominations": 50000,
        "typedenominations": null,
        "status": "1",
        "maker_id": "thudtl",
        "maker_date": "2021-04-22T14:17:18",
        "checker_id": "hieupx",
        "checker_date": "2022-04-21T10:56:11",
        "ord": 4,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "1c5cb733-e53f-41a7-9241-c4f9a3b2bb58",
        "ccy": "VND",
        "denominations": 20000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": null,
        "checker_date": null,
        "ord": 5,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "116b8430-6ad4-4809-9ac9-eeaf3978e1e8",
        "ccy": "VND",
        "denominations": 10000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": null,
        "checker_date": null,
        "ord": 6,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "72d41142-1ea6-471f-a9db-4c47e35f47da",
        "ccy": "VND",
        "denominations": 5000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": "lamht",
        "checker_date": "2021-04-20T10:35:27",
        "ord": 7,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "e51895c9-65e0-4bcf-b65c-48afc5676329",
        "ccy": "VND",
        "denominations": 2000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": "lamht",
        "checker_date": "2021-04-20T13:10:29",
        "ord": 8,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "46f96a99-8909-42f4-8c28-3e84dcd5a0b2",
        "ccy": "VND",
        "denominations": 1000,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": null,
        "checker_date": null,
        "ord": 9,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "fee73ede-4270-44fa-a98e-ff64eb98c48c",
        "ccy": "VND",
        "denominations": 500,
        "typedenominations": null,
        "status": "1",
        "maker_id": null,
        "maker_date": null,
        "checker_id": "hieupx",
        "checker_date": "2022-03-17T13:49:46",
        "ord": 10,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    },
    {
        "id": "dafa854f-75f4-4b76-bfeb-a443de804fa0",
        "ccy": "VND",
        "denominations": 200,
        "typedenominations": null,
        "status": "1",
        "maker_id": "hieupx",
        "maker_date": "2021-10-06T15:37:17",
        "checker_id": "hieupx",
        "checker_date": "2021-10-23T10:46:44",
        "ord": 11,
        "modify_id": null,
        "modify_date": null,
        "log": null,
        "heal_torn_coin": "HEAL"
    }
]